# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.9
_src_path: https://github.com/stellarshenson/copier-data-science
author_name: Stellars Henson
custom_config: ''
dataset_storage: none
dependency_file: pyproject.toml
description: Data science analysis of demographic collapse
docker_support: 'No'
docs: none
env_encryption: 'Yes'
env_name: sci-demographic-collapse
environment_manager: uv
git_init: 'Yes'
jupyter_kernel_support: 'Yes'
linting_and_formatting: ruff
module_name: sci_demographic_collapse
open_source_license: MIT
package_repository: 'No'
pydata_packages: none
python_version_choice: '3.13'
repo_name: sci-demographic-collapse
testing_framework: pytest
